---
title: "Analysis of video data from each run "
output:
  rmarkdown::html_document:
    theme: darkly
    fig_width: 10
    fig_height: 4
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir= normalizePath('..'))
library(ggplot2)
library(dplyr)
library(plotrix)
library(readr)
library(knitrBootstrap)



```


#  {.tabset}
## Introduction
Things which is been analysed throughout the project: </br>
  <ol>
   <li> Total views </li>
   <li> Total downloads </li>
   <li> Participants </li> 
   <li> Key factor derived from the data </br>
</ol>
## Run 3

In run 3, total number of views is  9607 and total number of downloads 756
```{r}
vidstats3 <- read.csv("~/Downloads/mooc-dataset-201920/cyber-security-3_video-stats.csv")
tv <- sum(vidstats3$total_views)
Steps <- vidstats3$step_position
b <- vidstats3$total_downloads
c <- vidstats3$total_views
par(mfrow=c(1,2))
plot(Steps, b,
main="Downloads of videos",
ylab="",
type="l",
col="blue")

plot(Steps, c,
main="Total views of videos",
ylab="",
type="l",
col="red")

slices <- c(59.59,	4.12,	20.21,	6.69,	2.96,	5.79) 
lbls <- c("Europe", "Ocenia", "Asia", "North America", "South America", "Africa")
pct <- round(slices/sum(slices)*100)
lbls <- paste(lbls, pct) # add percents to labels 
lbls <- paste(lbls,"%",sep="") # ad % to labels 
pie(slices,labels = lbls, col=rainbow(length(lbls)),
   main="Pie Chart of Countries")

```
 
## Run 4
```{r}



vidstats4 <- read.csv("~/Downloads/mooc-dataset-201920/cyber-security-4_video-stats.csv")
Steps <- vidstats4$step_position
b <- vidstats4$total_downloads
c <- vidstats4$total_views
par(mfrow=c(1,2))
plot(Steps, b,
main="Downloads of videos",
ylab="",
type="l",
col="blue")

plot(Steps, c,
main="Total views of videos",
ylab="",
type="l",
col="red")

slices <- c(59.59,	4.12,	20.21,	6.69,	2.96,	5.79) 
lbls <- c("Europe", "Ocenia", "Asia", "North America", "South America", "Africa")
pct <- round(slices/sum(slices)*100)
lbls <- paste(lbls, pct) # add percents to labels 
lbls <- paste(lbls,"%",sep="") # ad % to labels 
pie(slices,labels = lbls, col=rainbow(length(lbls)),
   main="Pie Chart of Countries")
```

## Run 5
```{r echo=FALSE}
vidstats5 <- read.csv("~/Downloads/mooc-dataset-201920/cyber-security-5_video-stats.csv")
Steps <- vidstats5$step_position
b <- vidstats5$total_downloads
c <- vidstats5$total_views
par(mfrow=c(1,2))
plot(Steps, b,
main="Downloads of videos",
ylab="",
type="l",
col="blue")

plot(Steps, c,
main="Total views of videos",
ylab="",
type="l",
col="red")

slices <- c(59.59,	4.12,	20.21,	6.69,	2.96,	5.79) 
lbls <- c("Europe", "Ocenia", "Asia", "North America", "South America", "Africa")
pct <- round(slices/sum(slices)*100)
lbls <- paste(lbls, pct) # add percents to labels 
lbls <- paste(lbls,"%",sep="") # ad % to labels 
pie(slices,labels = lbls, col=rainbow(length(lbls)),
   main="Pie Chart of Countries")
```

## Run 6
```{r echo=FALSE}
vidstats6 <- read.csv("~/Downloads/mooc-dataset-201920/cyber-security-6_video-stats.csv")
Steps <- vidstats6$step_position
b <- vidstats6$total_downloads
c <- vidstats6$total_views
par(mfrow=c(1,2))
plot(Steps, b,
main="Downloads of videos",
ylab="",
type="l",
col="blue")

plot(Steps, c,
main="Total views of videos",
ylab="",
type="l",
col="red")

slices <- c(59.59,	4.12,	20.21,	6.69,	2.96,	5.79) 
lbls <- c("Europe", "Ocenia", "Asia", "North America", "South America", "Africa")
pct <- round(slices/sum(slices)*100)
lbls <- paste(lbls, pct) # add percents to labels 
lbls <- paste(lbls,"%",sep="") # ad % to labels 
pie(slices,labels = lbls, col=rainbow(length(lbls)),
   main="Pie Chart of Countries")


```

## Run 7
There are in total 13 videos. Total num
```{r echo=FALSE}
vidstats7 <- read.csv("~/Downloads/mooc-dataset-201920/cyber-security-7_video-stats.csv")
Steps <- vidstats7$step_position
b <- vidstats7$total_downloads
c <- vidstats7$total_views
par(mfrow=c(1,2))
plot(Steps, b,
main="Downloads of videos",
ylab="",
type="l",
col="blue")

plot(Steps, c,
main="Total views of videos",
ylab="",
type="l",
col="red")

slices <- c(59.59,	4.12,	20.21,	6.69,	2.96,	5.79) 
lbls <- c("Europe", "Ocenia", "Asia", "North America", "South America", "Africa")
pct <- round(slices/sum(slices)*100)
lbls <- paste(lbls, pct) # add percents to labels 
lbls <- paste(lbls,"%",sep="") # ad % to labels 
pie(slices,labels = lbls, col=rainbow(length(lbls)),
   main="Pie Chart of Countries")


```

## Key Points



